[versions]
jdk = "25"
minecraft = "26.1.2"
fabric-loader = "0.19.5"
fabric-api = "0.155.2+26.1.2"
loom = "1.17.20"
modmenu = "18.0.0"
cloth-config = "26.1.154"

[libraries]
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
cloth-config = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "cloth-config" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
